import { TaskProvider } from "@/context/TaskContext";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark bg-gray-600">
      <body className={inter.className}>
        <TaskProvider>
          <NavBar />
          {children}
          <Toaster/>
        </TaskProvider>
      </body>
    </html>
  );
}
